version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drona-backend
    ports:
      - "8000:8000"
    environment:
      - CHROME_HEADLESS=True
    restart: unless-stopped
    networks:
      - drona-network

  frontend:
    build:
      context: https://github.com/drona/drona-web.git
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    container_name: drona-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - drona-network

networks:
  drona-network:
    driver: bridge
